### ISSUE TITLE
Request for installation of sklearn-crfsuite

### ISSUE THREAD

**Issue by celebrimbor-mak** [Kaggle/docker-python#1025]
Hi,

I was unable to find any implementation of CRF in the base kernel. I did install the package using my notebook, but the competition requires internet to be disabled. Hence, I am not able to make submissions. CRF is a pretty common algorithm, **sklearn-crfsuite** is a good implementation of the same. However, the current build does not support sklearn > 0.23.x. The following steps are to be followed for installation:

1. pip install 'scikit-learn<0.24'
2. pip install sklearn-crfsuite

Thanks

**Comment by rosbo** [comment]
We won't downgrade `scikit-learn` for this package given that other packages are depending on `scikit-learn` latest updates. You can work with the `sklearn-crfsuite` package author to support `scikit-learn` > 0.23.x

However, we have to limit the packages in our image due to size/complexity, so we won't generally accept a package with fewer than 1000 stars on GitHub.

If the package gains additional popularity & works with the latest version of `scikit-learn`, we might reconsider.
