### ISSUE TITLE
Problem with ANTsPy

### ISSUE THREAD

**Issue by rafaloz** [Kaggle/docker-python#1053]
I am trying to use the library ANTsPy for one of Kaggle's challenges. However, it seems that when importing the library something goes wrong. I get the message: 

RuntimeError Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of NumPy is 0xd

My main problem is when committing my notebook. The error appears and the commit fails. 

I've tested using different combinations of versions of NumPy and ANTsPy however, that doesn't solve the problem. I've tried also to upgrade NumPy and install ANTsPy, as many threads in google suggest, but it still fails. I don't know if you have an explanation for the error, I read several threads saying it's a pip's problem, handling different versions of NumPy, but I've tested the problem also just with the "default" 1.19.5 NumPy version, and from the installation output, I haven't seen any other version installed but it still fails. 

Here is an example of my problem: 

https://www.kaggle.com/ranafago/notebook68e3431a3e/edit

**Comment by rosbo** [comment]
Hi @rafaloz,

The issue is that `numpy` is imported when a session starts (before it runs your code).

Running `!pip install numpy=XYZ` will update the files on disk but the old version is still loaded in memory: https://www.kaggle.com/rosebv/antspy/edit/run/68799665 (see how np.__version__ still prints 1.19.5).

In an interactive session, you can get around by running the `pip install` command and then "Restarting" the notebook. However, this is not possible when "committing" a notebook.

Using `importlib#reload` can sometime work to reload a module from disk but it doesn't for numpy.

Unfortunately, I don't have a great solution for you.

We will eventually upgrade `numpy` eventually. However we are currently blocked because TensorFlow requires numpy `1.19.2`.

**Comment by rosbo** [comment]
One potential solution would be to compile `ANTsPy` from source against numpy `1.19.2` and it may work: https://github.com/ANTsX/ANTsPy/blob/master/tutorials/InstallingANTsPy.md#method-4-development-installation

**Comment by giemmecci** [comment]
@rafaloz 

Did you find a way around this issue? Thanks

**Comment by rafaloz** [comment]
Hey @giemmecci, 

I couldn't get around the issue, I guess the best is to wait for the tf update. The guys from AntsPy told me that they are not using NumPy for the build so I guess is a weird dependency. https://github.com/ANTsX/ANTsPy/issues/291
