### ISSUE TITLE
Torch Tensor RT 1.3.0

### ISSUE THREAD

**Issue by MPWARE-TEAM** [Kaggle/docker-python#1210]
### New feature
Torch Tensor RT 1.3.0
It requires:
- Pytorch 1.13.1 / Cuda 11.7
- Torchvision 0.14.1
- Tensor RT 8.5.2

It looks like it's not so easy as I've noticed some issues with code under torch_tensorrt/fx package when importing torch_tensorrt

Sources:
- https://github.com/NVIDIA/TensorRT
- https://github.com/pytorch/TensorRT

### Motivation
Allow compilation and execution of (most) models as Torch script much faster than regular inference. Useful for "Code" competitions.

**Comment by SohierDane** [comment]
Context on the speedups that competitors are realizing by installing the tensorrt from wheels: https://www.kaggle.com/competitions/rsna-breast-cancer-detection/discussion/375881

**Comment by djherbis** [comment]
I think that CUDA requirement is a dealbreaker for putting it in the image @SohierDane #1182 is the closest we've gotten to a CUDA upgrade (we rely on the DLVM base image upgrades happening first) and that's still only getting us to CUDA 11.3.

I think this is a case where it's best if users manually install this since it will break other things in the image, but they don't have to care about that since they know which packages they need to work.
