### ISSUE TITLE
AttributeError: module 'torch.cuda' has no attribute 'is_avaliable'

### ISSUE THREAD

**Issue by Aisuko** [Kaggle/docker-python#1266]
## 🐛 Bug

```
# cuda for Nvidia, mps stands for Metal Performance Shaders on Apple
torch_device="cuda" if torch.cuda.is_avaliable() else "cpu"
vae.to(torch_device)
text_encoder.to(torch_device)
unet.to(torch_device)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 2
      1 # cuda for Nvidia, mps stands for Metal Performance Shaders on Apple
----> 2 torch_device="cuda" if torch.cuda.is_avaliable() else "cpu"
      3 vae.to(torch_device)
      4 text_encoder.to(torch_device)

AttributeError: module 'torch.cuda' has no attribute 'is_avaliable'
```

### To Reproduce

Running code in this cell below
https://www.kaggle.com/code/aisuko/constructing-diffusers-sd-pipeline?scriptVersionId=134889144&cellId=8

**Comment by djherbis** [comment]
This worked for me:
```python
import torch
if torch.cuda.is_available():
    torch_device="cuda"
else:
    torch_device="cpu"
print(torch_device)
```

So I'm guessing its a syntax issue with using the inlined `if` statement.

**Comment by Philmod** [comment]
There is a typo in `is_avaliable`

**Comment by Aisuko** [comment]
Thanks for your quick reply, I checked the environment.

```python
import os, platform

torch_device = 'cpu'

if 'kaggle' in os.environ.get('KAGGLE_URL_BASE','localhost'):
    torch_device = 'cuda'
else:
    torch_device = 'mps' if platform.system() == 'Darwin' else 'cpu'
```

**Comment by thiswillbeyourgithub** [comment]
If anyone else has this issue: in my case it was caused by torch 2.9.1+cu130 being installed incorrectly by `uv` 0.7.0. When opening a python console and typing `import torch ; dir(torch)` I could see that is was basically empty. Same for `from torch import cuda ; dir(cuda)`.

The command that fixed it:
`pip install torch==2.9.1+cu130  --index-url https://download.pytorch.org/whl/cu130 --force-reinstall --user`
Maybe the `--user` part is only for my specific setup though. Reinstalling with `uv` instead of `pip` did NOT work.
