### ISSUE TITLE
ssh broken due to openssl version mismatch in gpu docker image

### ISSUE THREAD

**Issue by NahsiN** [Kaggle/docker-python#1267]
## 🐛 Bug

Accessing ssh is broken in the latest v134 - GPU docker image due to what I believe is an openssl version mismatch error.

### To Reproduce

```
docker run -it --rm  \
                --name kaggle-test \
                gcr.io/kaggle-gpu-images/python:v134 \
                /bin/bash
```

Once in the container, run `ssh -V`. Instead of showing the version, the following message is thrown
```
OpenSSL version mismatch. Built against 30000020, you have 30100010
```

A similar message is thrown if one tries to run related programs such as `ssh-keygen`

### Expected behavior

`ssh -V` should output something similar to 

```
OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1t  7 Feb 2023
```

### Additional context
I believe issue  involves an upstream bug in Ubuntu 22.04.2 LTS. It is related to https://github.com/msys2/MSYS2-packages/issues/3660

**Comment by djherbis** [comment]
ssh isn't really a supported use case anyway on our machines, what do you need to ssh into the machine for instead of using the editor?

**Comment by willlllllio** [comment]
Just ran into that, but only on GPU instance, my usecase is `rsync` a dataset from my server not sshing into it.

**Comment by PashaM999** [comment]
I would really appreciate if some kind of solution is found. Similarly to @willlllllio, I use this to `scp` files from my server. It is super inconvenient to download all the datasets to my PC first, especially given that some of them are updated frequently.

**Comment by PashaM999** [comment]
@djherbis As I said, almost all of them are not static. Moreover, even if not, I am not really keen on downloading tens of gigabytes on my PC each time I want to upload something. Not only does it take more than twice as much time because of the added download time, but also the internet that I have is much slower than Google's making the process take ages to complete. Using ssh I can just run the code and save the result as a dataset right away.

**Comment by djherbis** [comment]
It's only by learning more about what your use case is that we can help make it work. We want to help make data science easier, and have a lot of tools already we hope you can leverage.

You could ssh into your server, and then use the kaggle CLI to upload from your server to kaggle datasets.

You can also consider using an older kaggle notebook with "original" docker env where ssh works.

Tunneling isn't something we actively support, it's a lot already to try and make the packages work together. We'd appreciate it if anyone wants to contribute a fix or wait for a future release where it might fix itself.

**Comment by fecet** [comment]
```
!mamba install openssh -y
```
works for me.

I see many mamba in docker file, why not just use a `yaml` to manage them?

**Comment by djherbis** [comment]
@fecet Do you mean why don't we use a mamba yaml config file instead of directly installing like we do today?

It would be nice to move towards using env files, however currently we're not sure how much of the image relies on intermediary packages which are installed in different ways (different package managers, sometimes hacky fixes in between).

**Comment by NahsiN** [comment]
Fair question @djherbis but pardon my delay. I use the `ssh` protocol to sync git repos with my docker-python container. During DS experimentation work, I find it useful to sync with repos, use the jupyter lab git plugin etc.

**Comment by vduck** [comment]
> !mamba install openssh -y

It really works, thanks!

**Comment by stgkrt** [comment]
```
ENV LD_LIBRARY_PATH=/usr/local/lib
```
work for me. add this to Dockerfile
