### ISSUE TITLE
Ultralytics YOLOv8 Kaggle CPU notebook running deprecated Python 3.7

### ISSUE THREAD

**Issue by glenn-jocher** [Kaggle/docker-python#1358]
## 🐛 Bug

Python 3.7 end-of-life was more than 6 months ago but Kaggle is still running it on CPU notebooks causing our users to raise bug  reports at https://github.com/ultralytics/ultralytics when they are not able to install the latest package requiring Python>=3.8.0.

See https://devguide.python.org/versions/ for end of life details on the various Python versions.

## Reproduce

https://www.kaggle.com/code/ultralytics/yolov8/edit/run/138401128

<img width="1928" alt="Screenshot 2024-01-22 at 18 48 46" src="https://github.com/Kaggle/docker-python/assets/26833433/ae7df70e-765e-40b7-b4d6-ad369d27e988">

## Originally raised in 

https://github.com/ultralytics/ultralytics/issues/7729

**Comment by calderjo** [comment]
closing out this old bug...

since this post, we have upgraded to python 3.10.13 on newer notebooks.
We are able install latest Ultralytics (8.2.26) via pip on cpu. 

this have been self-resolved.

<img width="772" alt="Screenshot 2024-05-30 at 11 04 33 AM" src="https://github.com/Kaggle/docker-python/assets/64660690/bac4e20d-cee8-4424-8e3c-d0cbce0082f7">
