### ISSUE TITLE
Can't Install Krippendorff

### ISSUE THREAD

**Issue by MundusJournalism** [Kaggle/docker-python#1368]
I have the code "pip install krippendorff" but it doesn't seem to work.

("import krippendorff" gives the standard error that shows it hasn't been loaded.)

I'm using Kaggle.com and I get this error over and over for "pip install krippendorff":

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ddcaec0dbd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/krippendorff/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ddcaec0ded0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/krippendorff/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ddcaec0e170>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/krippendorff/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ddcaec0e320>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/krippendorff/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ddcaec0e4d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/krippendorff/
ERROR: Could not find a version that satisfies the requirement krippendorff (from versions: none)
ERROR: No matching distribution found for krippendorff

Thanks for the help!

**Comment by calderjo** [comment]
this may be due to having internet access on your notebook turned off, did run this on my notebook and it worked without any additional help. 

i did get the same error when turning internet off.
<img width="1647" alt="Screenshot 2024-05-15 at 12 46 09 PM" src="https://github.com/Kaggle/docker-python/assets/64660690/3aa8151e-9585-4a7e-b8e5-4f8bf95baccc">

with internet on:
<img width="1641" alt="Screenshot 2024-05-15 at 12 51 56 PM" src="https://github.com/Kaggle/docker-python/assets/64660690/dd26a025-9cb7-4cb0-93ea-c50d3bb1140f">

As a general note:
We do not guarantee that packages not pre-installed in our docker image to work right off the bat.

**Comment by calderjo** [comment]
removed bug tag, since krippendorff is not apart of our package offerings.

**Comment by calderjo** [comment]
krippendorff is a low-usage package based on our "github stars requirements" to add to our base image.

as mentioned above, i was able to install on a new notebook on both cpu/gpu. please reach out to kaggle community for support on python/pip usage.
