### ISSUE TITLE
RDKit library for chemical data processing

### ISSUE THREAD

**Issue by masun** [Kaggle/docker-python#1412]
Dear Sirs,
I am organizing a competition on the Kaggle platform, where the RDKit library needs to be installed to create my own score metric for the competition evaluation. The notebook for the personalized evaluation metric does not have internet access, so the !pip install rdkit command cannot be used. The "Internet off" setting cannot be changed.

Thank you, and I look forward to your prompt reply.

Best

**Comment by calderjo** [comment]
Hi, thanks for reaching out to me and the team, 

yeah internet off setting is intentional for cheating prevention, 
we are actively reducing our package offering, this is due to high maintenance burden.  

if this is for a community competition?

i might consider pushing this request if this is for a feature/research competition.

**Comment by calderjo** [comment]
thanks this info helps us, i will reach out to the other maintainers and competition admins about this request.

to mention again we're being a more strict on adding packages and the pace that we are releasing new images.

will get back to you about this.

**Comment by calderjo** [comment]
Hi someone on the comp team will follow up on your request with possible solutions, you may reopen this if you find those solution not possibe
