### ISSUE TITLE
h2o import fails

### ISSUE THREAD

**Issue by jarekszymczak** [Kaggle/docker-python#18]
Hi guys,

I have just pulled recent image of kaggle/python from docker repo, and I face the following problem when trying to import h2o:

````
In [1]: import h2o
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-707498249ab8> in <module>()
----> 1 import h2o

/opt/conda/lib/python3.4/site-packages/h2o/__init__.py in <module>()
    398 __version__ = "3.6.0.8"
    399 from h2o import *
--> 400 from model import *
    401 from demo import *
    402 from h2o_logging import *

ImportError: No module named 'model'
````

I have checked and same issue is on kaggle scripts, when running it on kaggle website

**Comment by nerdcha** [comment]
@jarekszymczak Just realised I didn't reply to this — sorry for the silence! I started looking in to this when you reported it, but it got steamrolled by a persistent issue on Docker Hub that took quite a while to sort out. We're now in a position where we can update our builds properly and we've pushed a few more recent deployments. I think the problem seems to have been fixed with the updated h2o install. Could you please confirm?

Thanks very much for the bug report, and apologies again for the delay in getting back to you.

**Comment by nerdcha** [comment]
The h2o installs seem to have been rolling along ok, so I'll close this issue.

**Comment by jarekszymczak** [comment]
Hey, sorry for not replying immediately, I still haven't checked whether
this works (import h2o does, but of course it worked on kaggle scripts, so
you knew that, I haven't tried anything with h2o so far).

Thanks a lot for tackling the problem and I'd like to say, that kaggle
docker python image is really wonderful thing! :)

2016-05-02 1:22 GMT+02:00 Jamie Hall <notifications@github.com>:
