### ISSUE TITLE
Unable to pull this image: "No space left on device"

### ISSUE THREAD

**Issue by dsifford** [Kaggle/docker-python#19]
Hi there.

I tried pulling this image this evening and received this error about halfway through:

```sh
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/local/src/opencv/build/modules/video/perf_precomp.hpp.gch/opencv_perf_video_RELEASE.gch: no space left on device
```

What's interesting is, I know that I am not out of space. I'm running arch linux as my host, and I just finished creating a 1TB partition exclusively for the `/var` directory on my machine. Before the pull there was 869.9 gigs of space available.

Any suggestions on what I should do here?

Thanks. I appreciate the help!

**Comment by nerdcha** [comment]
That error sounds puzzling, and frustrating. I haven't heard of it happening to anyone else, though, so I suspect it's going to be an issue for Docker rather than us.

My first suggestion would be to try pulling another large image, to figure out if the bug happens for all large ones or just this one.

Secondly, you could restart Docker in debug mode, so it outputs more verbose logs about what it's doing. You can do that via the [daemon](https://docs.docker.com/engine/reference/commandline/daemon/) or IIRC by sticking a "-D" switch in `/etc/default/docker`. That might reveal that it's trying to write somewhere outside `/var` for something else weird like that.

Beyond that, my next suggestion would be to contact Docker's [support](https://support.docker.com). I'll keep the Issue open in case you need anything else from us, or if others want to chime in. Good luck!

**Comment by dsifford** [comment]
Wilco. Thanks -- I'll keep you posted if something turns up.

**Comment by dsifford** [comment]
Closing this issue. I unfortunately was not able to figure out why the build was failing, even after speaking with Docker support. I decided to just go with `jupyter/datascience-notebook` instead as that serves my needs.

Thanks

**Comment by KhaoticMind** [comment]
I'm having this same error :/

I tried pulling the images by parts, and the error happens when pulling python3 image.
Running docker on debug mode gives me this output  (cut on the part that matters).
```
DEBU[0756] Downloaded c6d2443e2638 to tempfile /var/lib/docker/tmp/GetImageBlob289671022 
DEBU[0756] pulling blob "sha256:4b3fb301ac5153c42468ee992a7e555741ac8a6eea9f8201353e7893a21079bb" 
DEBU[0759] Increasing token expiration to: 60 seconds   
DEBU[0765] Downloaded 4b3fb301ac51 to tempfile /var/lib/docker/tmp/GetImageBlob966782453 
DEBU[0896] Downloaded ab3ce72e34fa to tempfile /var/lib/docker/tmp/GetImageBlob189660721 
DEBU[0896] devmapper: AddDevice(hash=0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98 basehash=e893e0bd9d694597ee47d7d5ee644c854cce641b3d81a647cb0fc1eaf9c3685d) 
DEBU[0896] devmapper: registerDevice(91, 0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0896] devmapper: AddDevice(hash=0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98 basehash=e893e0bd9d694597ee47d7d5ee644c854cce641b3d81a647cb0fc1eaf9c3685d) END 
DEBU[0896] devmapper: activateDeviceIfNeeded(0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0896] Start untar layer                            
DEBU[0915] devmapper: UnmountDevice(hash=0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0915] devmapper: Unmount(/var/lib/docker/devicemapper/mnt/0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0916] devmapper: Unmount done                      
DEBU[0916] devmapper: deactivateDevice(0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0916] devmapper: removeDevice START(docker-8:6-22675468-0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0916] devmapper: removeDevice END(docker-8:6-22675468-0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0916] devmapper: deactivateDevice END(0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0916] devmapper: UnmountDevice(hash=0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) END 
DEBU[0916] Cleaning up layer 0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98: ApplyLayer exit status 1 stdout:  stderr: write /usr/local/src/opencv/build/modules/core/perf_precomp.hpp.gch/opencv_perf_core_RELEASE.gch: no space left on device 
DEBU[0916] devmapper: DeleteDevice(hash=0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98 syncDelete=false) START 
DEBU[0916] devmapper: issueDiscard(device: 0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98). START 
DEBU[0916] devmapper: activateDeviceIfNeeded(0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0918] devmapper: issueDiscard(device: 0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98). END 
DEBU[0918] devmapper: deactivateDevice(0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0918] devmapper: removeDevice START(docker-8:6-22675468-0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0918] devmapper: removeDevice END(docker-8:6-22675468-0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0918] devmapper: deactivateDevice END(0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0918] devmapper: unregisterDevice(91, 0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98) 
DEBU[0918] devmapper: DeleteDevice(hash=0d7e4d2a393befad976972d063e66bcda8a27171d12ef6f6e5b01c5418a77c98 syncDelete=false) END 
```

As @dsifford I have plenty of space on my device.
I'll try building the images using the dockerfile and see what happens.

**Comment by ThomasDelteil** [comment]
Same error for me 
ApplyLayer exit status 1 stdout:  stderr: write /usr/local/src/opencv/build/modules/core/perf_precomp.hpp.gch/opencv_perf_core_RELEASE.gch: no space left on device

**Comment by KhaoticMind** [comment]
Found the issue (in my case).
For what I've read docker create new containers with a default image size of 10GB (https://docs.docker.com/v1.10/engine/reference/commandline/daemon/ , search for dm.basesize).

For what I get most distros already change it, but on my Gentoo system it is keeping the defaults.
What I did to fix the issue was to stop docker, clean /var/lib/docker/ (I'm running on a loopback device), start docker with the command:

``
docker daemon --storage-opt dm.basesize=40G
``

Stop it and restart the docker service as usual.
This fixed the issue for me, and a new `docker pull kaggle/python` finished without issues.

Not sure If you had to delete /var/lib/docker (I had nothing on it, so I decided to start clean anyway).

**Comment by ThomasDelteil** [comment]
Thanks it solved the problem indeed! :+1:

**Comment by naruto2302** [comment]
Try 
`df -i` 
for more disk space info 
`sudo docker system prune`
for clear trash

**Comment by antgwms** [comment]
Thanks @KhaoticMind I restarted docker and it worked great 👍

**Comment by LN-Curiosity** [comment]
My storage-driver is overlay2.How can i set the parameter about size in the  /etc/docker/daemon.json?

**Comment by rushins** [comment]
hello i got the same issue , i created this file and added the value and restarted docker , however the problem persists . my docker is centos 7 . Any idea how to fix this.
-----
more /etc/sysconfig/docker-storage
DOCKER_STORAGE_OPTIONS= "--storage-opt dm.basesize=60G"
