### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.impute'

### ISSUE THREAD

**Issue by llucifer97** [Kaggle/docker-python#353]
sklearn.impute is not avilable

**Comment by xiechen0620** [comment]
I have the same problem.
The version of scikit-learn was 0.21.dev0 before, and now it is 0.19.1
I don't know why roll back this package.
Pls update scikit-learn.

**Comment by alpesh1122** [comment]
I am also facing problem.
ModuleNotFoundError: No module named 'sklearn.impute'

**Comment by steppeulv** [comment]
Same, worked a while back with my kernels

**Comment by alpesh1122** [comment]
looks like you can use this instead

from sklearn.preprocessing import Imputer

**Comment by rosbo** [comment]
Hi, sklearn has been updated to `0.20.1`.

```
import sklearn
print(sklearn.__version__)
0.20.1
```

And `sklearn.impute` is now present:

```
from sklearn import impute
dir(impute)
[..., ma, map, np,...]
```

**Comment by sahilpatni95** [comment]
ModuleNotFoundError: No module named 'sklearn.impute'

**Comment by garyee** [comment]
I had the same error today.

Could it be because I'am (and @sahilpatni95 is also) using the docker image called kaggle/python from the [docker hub](https://hub.docker.com/r/kaggle/python) which has not been updated since two years.
If I understand the ReadMe correctly, the latest docker image is on [google](https://console.cloud.google.com/gcr/images/kaggle-images/GLOBAL/python?gcrImageListsize=30)

You could maybe consider updating the [medium article](https://medium.com/@kaggleteam/how-to-get-started-with-data-science-in-containers-6ed48cb08266) or to update the docker image on docker hub at least once a year or so, to avoid people having these obsolete kind of errors.

**Comment by rosbo** [comment]
Hi @garyee,

You are correct, we have stopped maintaining the `kaggle/python` image and using only `gcr.io/kaggle-images/python`.

I will make sure the Medium article gets updated. Thanks for flagging.

**Comment by sahilpatni95** [comment]
> Hi @sahilpatni95
> 
> The latest version of our environment has `sklearn` 0.23.1 which includes `sklearn.impute`.
> 
> Can you run the following and paste the output please:
> 
> ```
> import sklearn
> print(sklearn.__version__)
> ```
> 
> Thank you

Thanks

**Comment by azhar2u** [comment]
import sklearn as l
print(l.__version__)

0.23.1

## Having no imputer into it

**Comment by ajayshelke** [comment]
import sklearn 
print (sklearn.__version__)
My scikit version shows 1.4.2 but I still get the error ModuleNotFoundError: No module named 'sklearn.imputer'
Any suggestions ?
