### ISSUE TITLE
IPython.lib.display.IFrame not working

### ISSUE THREAD

**Issue by daavoo** [Kaggle/docker-python#36]
When running code like the following in a notebook :

``` python
from IPython.display import IFrame
IFrame('http://stackoverflow.org', width=700, height=350)
```

There is no output.

Is this behaviour intended??

**Comment by nerdcha** [comment]
Could you clarify — are you running this locally, or on kaggle.com? If it's the latter, then yes: our free public kernels do not have external internet access.

**Comment by daavoo** [comment]
Hi there! 

I'm talking about running the notebook on kaggle.com.

Good to know the fact that kernels don't have internet but I don't think that in my case the problem is related to  that.

More specifically, what I'm able to do locally but I can't make on kaggle.com is to create an html file and display it on the notebook via IFrame. A simplified example:

```python
with open("out.html", "w") as html:
    html.write("<h1>HELLO IFrame!</h1>")
from IPython.display import IFrame
IFrame("out.html", height=200, width=200)
```

Thank you for your attention!

**Comment by nerdcha** [comment]
Ah, I see. The HTML returned from the Jupyter kernel gets sanitized by our front-end before being rendered, so I think the `<iframe>` tags are getting filtered out. We're aiming to support things like this, plus Javascript-based widgets and so on, but we can't do it immediately because our engineering resources are carefully rationed. Hopefully soon, though!

**Comment by onclick360-blog** [comment]
I am using Jupyter [Notebook](https://onclick360.com/cost-function-in-machine-learning/) as a public server and accessing remotely when i am trying to run some plot with plotly it's not showing on my remote web browser its throw error "127.0.0.1 refused to connect." not sure in [iframe](https://onclick360.com/jenkins-installation-windows) how to use original server ip instead of 127.0.0.1.
