### ISSUE TITLE
Add new package keras_contrib

### ISSUE THREAD

**Issue by Franky1** [Kaggle/docker-python#489]
https://github.com/keras-team/keras-contrib

**Comment by rosbo** [comment]
We will move soon to TensorFlow 2.0. The recommended way to use Keras will be to use `tf.keras`. 

`keras.io` as of yesterday (9/17/2019) supports TensorFlow 2.0 as a backend but not all features and the recommended way to use keras is through `tf.keras`:

> This release brings the API in sync with the tf.keras API as of TensorFlow 2.0. However note that it does not support most TensorFlow 2.0 features, in particular eager execution. If you need these features, use tf.keras.

-- https://github.com/keras-team/keras/releases/tag/2.3.0

For this reason, we won't add `keras-contrib` at this points since it relies on the `keras.io` package.

Thank you
