### ISSUE TITLE
 FMA instructions not available on my machine p2

### ISSUE THREAD

**Issue by skw1990** [Kaggle/docker-python#604]
As referred to the comment quoted from: https://github.com/Kaggle/docker-python/issues/248: 

> 1. Follow these instruction to build a custom Tensorflow wheels: https://github.com/Kaggle/docker-python/tree/master/tensorflow-whl
> 2. Update the following line in the [Dockerfile ](https://github.com/Kaggle/docker-python/blob/master/Dockerfile#L1) to the Tensorflow wheels image you built in the previous step:
> Replace `FROM gcr.io/kaggle-images/python-tensorflow-whl:1.11.0-py36 as tensorflow_whl` by `FROM kaggle/python-tensorflow-whl as tensorflow_whl`
> 3. Build the Kaggle image using this [build ](https://github.com/Kaggle/docker-python/blob/master/build) script.

My queries:

1. What to edit for step 1? 
2. How to build the image with the aforementioned script in win10 host? 
Edit:  I tried docker build - but there are 3 separate images in the _docker image ls_ which is kinda weird. 

Thanks if you can elaborate more on the above.

Thanks.

**Comment by skw1990** [comment]
Hi, thanks for responding. I don't understand how to build the custom tensorflow-whl with support to device without FMA or according to cpu requirement.

**Comment by skw1990** [comment]
Any comment on the above? I tried to add these near bazel build (_bazel build --copt=-mavx --copt=-msse4.1 --copt=-msse4.2 --config=opt //tensorflow/tools/pip_package:build_pip_package_ ) - but anyway the build is unsuccessful in the dockerhub. I just want to know how to custom build the tensorflow_flow.whl first .......

**Comment by rosbo** [comment]
@skw1990,

I suggest that you open an issue on the TensorFlow repo and make sure to include the build errors you are getting.

Thank you

**Comment by skw1990** [comment]
Hi, don't understand - why in Tensorflow repo? The above was based on the dockerfile in https://github.com/Kaggle/docker-python/tree/master/tensorflow-whl ... so this for this issue i should get back to tensorflow repo itself?

**Comment by rosbo** [comment]
The option I was suggesting was to build your own TensorFlow using only the instructions available on your machine. We don't offer support for this but looking at issue or asking help on the TensorFlow repo might have helped you achieve that.

Another simpler solution would be the following.

The image we build is optimized for the machines we are using to run Notebooks on the Kaggle platform. Instead of using our optimized pre-built TensorFlow wheel, I suggest you use the more generic (not arch optimized) TensorFlow version on a pip.

To do this, replace the following lines in `Dockerfile`:

```
COPY --from=tensorflow_whl /tmp/tensorflow_cpu/*.whl /tmp/tensorflow_cpu/
RUN pip install /tmp/tensorflow_cpu/tensorflow*.whl && \
    rm -rf /tmp/tensorflow_cpu && \
```

By:

```
pip install tensorflow==1.14.0
```

If you are using a GPU instead, you can use a similar transformation in the `gpu.Dockerfile` file.

Let me know if that solves your issue.

Thank you.

**Comment by skw1990** [comment]
Alright - this is helpful. Will try it out and see what's the outcome.
Many thanks.
