### ISSUE TITLE
pip installing clustergrammer2 only works after refreshing page

### ISSUE THREAD

**Issue by cornhundred** [Kaggle/docker-python#648]
Our Jupyter Widget Clustergrammer2 can be installed in-line using `!pip install clustergrammer2`, but only works after refreshing the page. This must have something to do with the front-end being updated. It used to work without a page refresh when we could pip install packages on the sidebar (see https://www.kaggle.com/cornhundred/heatmap-view-of-modern-era-nba-player-stats).

Also, the widget is not always embedded into the static HTML file, see https://www.kaggle.com/cornhundred/clustergrammer2-test-11-20-2019?scriptVersionId=23782833

I requested that the package be included in the docker image to overcome this issue:

https://github.com/Kaggle/docker-python/pull/647

**Comment by djherbis** [comment]
Installing via the sidebar was quite different to pip installing in your kernel.
The side-bar created a new Docker image that included the added package, which means that on startup of jupyter it would have the package pre-installed.

That's probably why refreshing is required, in order to load the widget into jupyter (best guess).

As for why it's not showing up in the static HTML file, I'm guessing that's because we execute the notebook to generate that, and since during execution the package is installed (but wouldn't be pre-execution), it's not available during that notebook execution (similar to the refresh issue).

I'm not sure yet what we can do about that, since we don't currently have a way to pre-install packages before executing the notebook.

**Comment by cornhundred** [comment]
Thanks @djherbis for the feedback!

### Page Refresh Required
When I execute the Kaggle notebook without refreshing the page I do not see the widget and I see the following in the console log 

<img width="801" alt="Screen Shot 2019-11-21 at 9 17 02 AM" src="https://user-images.githubusercontent.com/8352840/69345837-cffa9400-0c3f-11ea-8da7-32242f112412.png">

The first line shows that Jupyter widgets extension is being loaded (`Loading extension: jupyter-js-widgets/extension`), but later it fails to instantiate the Clustergramemr2 widget. 

However, after refreshing the page the widget works and we see the following console output: 

<img width="792" alt="Screen Shot 2019-11-21 at 9 19 47 AM" src="https://user-images.githubusercontent.com/8352840/69346055-2667d280-0c40-11ea-82b4-248503bcfac9.png">

Would you know if there are any plans to bring back the pre-installed package option or if there is any way we would be able to get our package to be included in the default docker container (e.g. after showing broader use by the community, https://github.com/Kaggle/docker-python/pull/647)? 

We made a few tutorial videos showing how we can use Kaggle to analyze gene expression datasets: 
* Cancer Cell Line Encyclopedia: https://youtu.be/9vqLO6McFwQ
* Single Cell Gene Expression: https://youtu.be/f-snXe2Bn9Q

but the difficulty of installation is preventing us from really moving forward on these projects.

### Embedding the widget into the static HTML
I took a screenshot of an instance where the widget was correctly embedded into the static HTML of the notebook. But the widget embedding is finicky in that after switching the notebook to public the embedded widget no longer appeared (here's a public [notebook](https://www.kaggle.com/cornhundred/kernel74375c8a45?scriptVersionId=23819540) that used to show the widget in the static HTML, but no longer does).

<img width="1909" alt="Screen Shot 2019-11-21 at 7 25 20 AM" src="https://user-images.githubusercontent.com/8352840/69346152-51eabd00-0c40-11ea-931d-cc3c3d99dea8.png">

**Comment by djherbis** [comment]
Thanks for all the details, this is quite helpful.

Right now, I'm basically thinking the best thing we can try and find is if there is a way to trigger a reload of jupyter widgets while a notebook is executing (both interactively in our editor, and via nbconvert when "committed").

If we can find a way to accomplish that (I've forked your sample kernel and been trying experiments), then that'll be the simplest solution.

**Comment by cornhundred** [comment]
Thanks @djherbis that sounds good. I'll let you all know if I can think of anything else that might help. 

Also, I'll cc some Jupyter widgets folks below to see if they have any ideas:

FYI @jasongrout, @maartenbreddels, @SylvainCorlay we're working on getting my Jupyter Widget working on Kaggle and checking if you all have any advice. Hopefully anything we learn in this process will be useful for widgets in Kaggle in general.

**Comment by maartenbreddels** [comment]
Hi all,

would love to see some ipywidgets pre-installed (ipywidgets, ipyleaflet, ipyvolume, ipyvuetify, bqplot, ...)
> `pip install clustergrammer2`, but only works after refreshing the page.

This is expected, similar to a notebook, the page requests the installed extensions only on page load (pip install cannot trigger this).

The generated html (e.g. https://www.kaggle.com/maartenbreddels/kernel74375c8a45?scriptVersionId=23856887 ) seems to have a wrong url, I see a 404 to:

https://www.kaggleusercontent.com/kf/23856887/eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..uBC5QS1rym810gYhQR6ibA.xADq7nFKUpMzP0yPe4g7yoRfx2ccESBBV9igkZxXD6Ve4Vz7hg_ep-IItDSKGU3rMGN9dGGaL8UpyI_SmPRRK3ryIhtrVi6eEuGOowmgjd-VE0HksO1t23B-O6Yfm_4Q11ygTOc7YRSI9rFgulZZEuIOntxdZ_Px1565tMyzWuo.ZBT_UH_qdyBU4nC9V5Mj2g/@jupyter-widgets/html-manager@*/dist/embed-amd.js

If you look at for instance ipyvolume's docs: https://ipyvolume.readthedocs.io/en/latest/

It requests `https://unpkg.com/@jupyter-widgets/html-manager@%5E0.18.0/dist/embed-amd.js`

So this seems to be an issue on kaggle's side I think.

**Comment by djherbis** [comment]
@maartenbreddels Thanks for the context.

The bad url is particularly interesting to me, when I look at the generated HTML it's using a relative path for embed-amd.js which explains why it's not loading from the CDN. However, I don't really know what causes it to be written this way. I tried executing it on a second stack I'm working on and it wrote it with the entire URL. I'll keep investigating.

We usually set a decently high bar of usage / popularity for adding packages to the base image just because every package means larger images, and more dependency management/conflicts.

**Comment by djherbis** [comment]
@cornhundred I'm in the middle or rolling out some new stuff, one of which seems to fix this issue at least for commits.

If you share your Kaggle username, I can whitelist you to the fix to verify.

**Comment by cornhundred** [comment]
Hi @djherbis thanks my Kaggle account name is cornhundred.

**Comment by djherbis** [comment]
Whitelisted your account, feel free to try it out.

**Comment by cornhundred** [comment]
Thanks, @djherbis the embedding on a public notebook still seems a little unpredictable (e.g. it stopped working after I refreshed the page on my public notebook https://www.kaggle.com/cornhundred/kernel22c1e4da50). It is a little tricky to get the widget working in the kernel (it appears to require 1) pip installing , 2) refreshing the page, 3) then executing the rest of the notebook. I needed to make the kernel public before committing and I was able to see the widget in the HTML - but it stopped showing up after I refreshed the page. 

Also, in a separate minor issue my widget (which is pretty wide) is being cut off a little. I'm not sure if there's any flexibility in notebook rendering width.

**Comment by djherbis** [comment]
@cornhundred So it looks like it is working, however I've found a separate post-process which is supposed to enrich notebooks but seems to break the widget by changing the url away from embed-amd.js on unpkg.com. 

I'll work with the owner of that process tomorrow to fix that.

**Comment by djherbis** [comment]
We think we fixed the post-processor if you want to try again now.

**Comment by cornhundred** [comment]
It is working now https://www.kaggle.com/cornhundred/clustergrammer2-12-23-2019

**Comment by cornhundred** [comment]
Hi @djherbis, our widget is being saved correctly in the static HTML output from a kaggle notebook run (see https://www.kaggle.com/cornhundred/clustergrammer-2020-06-05?scriptVersionId=35499600). However, the HTML notebook is being rendered a little narrow for our needs and cutting off the right side of our visualization. Is there any way that the width could be increased (we just need ~75px more), as an option perhaps? 

I was thinking I might add in a hack to run something like this on our widget front-end if it sees that it is being rendered on Kaggle

```
document.getElementById("rendered-kernel-content").style.width = "975px";
```

Please let me know if there is a more appropriate place to raise this issue.

**Comment by djherbis** [comment]
@cornhundred  I don't think you can hack the width of that container because it's an iframe, modifying outside the iframe from inside it is a bit of a security risk. It also wouldn't likely always work as we may change the viewer at any time which could break this.

This setting isn't really related to the docker image either. Docker is the execution environment for your notebook, but the viewer is part of the Kaggle server which embeds your HTML-formatted notebook.

I've brought up your concerns to the design team for the viewer, but is there any reason your widget can't be responsive instead? The width of the viewer is somewhat responsive, and on smaller browser widths (ex. mobile) it won't have 1100px of space anyway.

**Comment by cornhundred** [comment]
Thanks @djherbis that makes sense. Yes, our widget isn't responsive yet, but it's generally useful for us to have more screen space for the heatmap so a wider option would be appreciated if possible.
