### ISSUE TITLE
Add prolog

### ISSUE THREAD

**Issue by jdvdv** [Kaggle/docker-python#761]
Hi all,

I'd like to add swi-prolog (a Prolog implementation) and pyswip (a prolog bridge for python) to the Dockerfile. This could, for instance, be useful for the Abstraction and Reasoning Challenge.

We could discuss whether swi-prolog is the best implementation, gnu-prolog is said to be more efficient, but there are slight differences and I think more people are used to swi-prolog (?)

Anyways, what do you all think? I could create a PR. I think I'll need some rights on this repo to create a branch though (or am I missing something?)

**Comment by rosbo** [comment]
Hi @jdvdv,

In an effort to limit the size of our Docker Python image and ease the maintenance burden, we are only pre-installing the popular packages into it (1000+ stars on GitHub).

You can still install the package in your notebook by following these instructions:
https://github.com/Kaggle/docker-python/wiki/Missing-Packages

You can also use the same approach with the `!` to run `!apt-get install` command or any bash command you may like.

> Anyways, what do you all think? I could create a PR. I think I'll need some rights on this repo to create a branch though (or am I missing something?)

Just a FYI as it won't be needed: you have to create a fork of this repo and open a PR from a branch in your fork against the master branch in this repo.

Thank you

**Comment by jdvdv** [comment]
Hi @rosbo ,

Thanks for your answer and the help. Makes sense not to include it.

Best,
Jos

**Comment by JamesMcGuigan** [comment]
I have created a kernel showing how Prolog can be used in a Kaggle Kernel
- https://www.kaggle.com/jamesmcguigan/n-queens-92-solutions-in-prolog

This approach does require internet access, so would not be suitable for a Kernel Only Competition

SWI Prolog has a combined 640 stars on its release and development github repositories
- https://github.com/SWI-Prolog/swipl
- https://github.com/SWI-Prolog/swipl-devel

Prolog has been around since the 70s, and whilst it never quite gained the popularity of imperative languages, it is the canonical example of the "logic programming" paradigm. Which is of specific relevance to artificial intelligence, computational linguistics research and possibly very interesting new avenue for exploring Kaggle Datasets.

Request to reopen this issue.

**Comment by rosbo** [comment]
Hi @JamesMcGuigan,

Thanks for creating a notebook showing how to use Prolog in Kaggle Notebook.

Unfortunately, for the reasons outlined above (https://github.com/Kaggle/docker-python/issues/761#issuecomment-607373339), Prolog is not a programming language we are planning to support as a first-class citizen at this time.

Thank you
