### ISSUE TITLE
install opencv from anaconda channel

### ISSUE THREAD

**Issue by hubutui** [Kaggle/docker-python#825]
Hey, it seems that this Docker image use opencv from conda-forge channel ([link](https://anaconda.org/conda-forge/opencv)), while there is a opencv available from anaconda channel ([link](https://anaconda.org/anaconda/opencv)). The one from conda-forge channel is lack of non-free algorithms, such as `sift, surf` from `xfeatures2d`. Could you consider replacing it with the one from anaconda channel? 
And may I ask why you install `opencv-python` using `pip` while we already have opencv installed by conda? ([link](https://github.com/Kaggle/docker-python/blob/master/Dockerfile#L343)).

**Comment by rosbo** [comment]
Hi @hubutui,

We are using `gcr.io/deeplearning-platform-release/base-cpu` as our base image. This base image includes `opencv` and several other packages. They are all from the `conda-forge` package. We try to deviate as little as possible from this base image to prevent dependencies conflict.

You are more than welcome to run a conda command in your own kernel to reinstall the anaconda version of opencv.

To answer your question about installing `opencv-python` using `pip`. This is because when this command was added (~2 years ago), our base image didn't include `opencv`. Now, this command is redundant and is a NoOp. From the build logs: `Requirement already satisfied: opencv-python`. I opened a PR to remove this redundant command. Thanks for flagging.
