### ISSUE TITLE
Problem with tf-nightly or tf>2.2

### ISSUE THREAD

**Issue by AakashKumarNain** [Kaggle/docker-python#850]
This may sound a bit odd and silly but I am unable to use `tf-nighlty` or `tf=2.3rco` in the notebooks. The weird thing is that almost 10 days ago, `tf-nightly` was working fine. Here is a screenshot for the same:

<img width="596" alt="Screenshot 2020-07-06 at 9 26 55 PM" src="https://user-images.githubusercontent.com/11736571/86613983-f2270380-bfcf-11ea-9e81-a2236dafd9a0.png">

**Comment by rosbo** [comment]
Hi @AakashKumarNain,

A bug slipped into our image where TensorFlow was preloaded when a kernel starts. This means that even if you reinstall a newer version of TensorFlow on disk, a call to `import tensorflow` will load the original version of tensorflow from memory. 

This has been fixed in #849 and will be part of our next bi-weekly release. 

For now, you can update the `Environment` setting in the Notebook Editor and set it to "Original". This will create your notebook inside the Docker image your notebook was originally created with.

**Comment by AakashKumarNain** [comment]
Thanks @rosbo for the update.
