### ISSUE TITLE
ERROR: Cannot connect to the Docker daemon at tcp:// . Is the docker daemon running?

### ISSUE THREAD

**Issue by rohitagarwal257** [Kaggle/docker-python#851]
I received the following error after 7 hours of GPU usage.

<img width="899" alt="Screenshot 2020-07-11 at 8 21 35 PM" src="https://user-images.githubusercontent.com/22426936/87232909-61419500-c3e0-11ea-9412-51e61a600533.png">

What does this mean? How to avoid? How do I recover the lost 7 hours?

Notebook link [here](https://www.kaggle.com/rohitagarwal/melanoma-gpu?scriptVersionId=38501986)

PS: My first time posting on GitHub, kindly pardon any malpractices.

**Comment by djherbis** [comment]
Hey, I replied on the forums:
https://www.kaggle.com/c/siim-isic-melanoma-classification/discussion/166006#931033

This GitHub is mostly related to managing which python packages are installed on Kaggle (though the error message does mention Docker, it's actually just a connection issue).

As I mentioned on the forums, this is usually caused by a rare maintenance event on host VMs.

Thanks for reporting it though, I'll continue to bug the team that's working on preventing these events from impacting us.
