### ISSUE TITLE
Numba gives a type error when compiling this trivial function

### ISSUE THREAD

**Issue by dah33** [Kaggle/docker-python#943]
See this post on Stack Overflow. It's almost certainly been fixed in a later version of Numba, as others were not able to recreate the issue.

https://stackoverflow.com/questions/65858762/numba-gives-a-type-error-when-compiling-this-trivial-function

**Comment by stuartarchibald** [comment]
Just guessing from the code sample, I think it will run into issues related to variable naming schemes which would create the noted problem in type inference. This was fixed by Numba 0.49 by the addition of full [SSA](https://en.wikipedia.org/wiki/Static_single_assignment_form) form in Numba's [IR](https://en.wikipedia.org/wiki/Intermediate_representation).

**Comment by rosbo** [comment]
Our `latest` Python Docker image for Kaggle notebooks now includes numba 0.52.0. 

I tested the code shared in the stackoverflow post and it works.

If you are still experiencing issues with `numba`, please feel free to reopen your PR.

Thank you
